# Generated by Django 4.1.1 on 2022-09-14 16:24

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_simple', models.CharField(blank=True, db_index=True, max_length=50)),
                ('title_selected', models.CharField(blank=True, db_index=True, max_length=50)),
                ('paragraph_1', models.TextField(blank=True, db_index=True, max_length=500)),
                ('paragraph_2', models.TextField(blank=True, db_index=True, max_length=500)),
                ('paragraph_3', models.TextField(blank=True, db_index=True, max_length=500)),
                ('selected_text_1', models.CharField(blank=True, db_index=True, max_length=200)),
                ('selected_text_2', models.CharField(blank=True, db_index=True, max_length=200)),
                ('selected_text_3', models.CharField(blank=True, db_index=True, max_length=200)),
                ('video_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('job_position', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('position', models.SmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('first_text_field', models.TextField(blank=True, db_index=True, max_length=200)),
                ('second_text_field', models.TextField(blank=True, db_index=True, max_length=200)),
                ('selected_text_1', models.CharField(blank=True, db_index=True, max_length=100)),
                ('selected_text_2', models.CharField(blank=True, db_index=True, max_length=100)),
                ('selected_text_3', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to=main.models.Events.get_file_name)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=300)),
                ('photo', models.ImageField(upload_to=main.models.Gallery.get_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='OurInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(max_length=100)),
                ('bottom_site_slogan', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('open_hours', models.CharField(max_length=200)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254)),
                ('phone_number_1', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number in format xxx xxx xxxx', regex='^(\\d{3}[- .]?){2}\\d{4}$')])),
                ('phone_number_2', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number in format xxx xxx xxxx', regex='^(\\d{3}[- .]?){2}\\d{4}$')])),
                ('twitter', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('skype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('profession', models.CharField(max_length=50)),
                ('review', models.TextField(max_length=300)),
                ('position', models.SmallIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_title', models.CharField(blank=True, db_index=True, max_length=300)),
                ('book_a_table_title', models.CharField(blank=True, db_index=True, max_length=300)),
                ('chefs_title', models.CharField(blank=True, db_index=True, max_length=300)),
                ('contact_us_title', models.CharField(blank=True, db_index=True, max_length=300)),
                ('why_us_title', models.CharField(blank=True, db_index=True, max_length=300)),
                ('special_title', models.CharField(blank=True, db_index=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TopSitePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('text', models.TextField(db_index=True, max_length=300)),
                ('position', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to=main.models.TopSitePresentation.get_file_name)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number in format xxx xxx xxxx', regex='^(\\d{3}[- .]?){2}\\d{4}$')])),
                ('persons', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date', '-is_processed'),
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan_1', models.CharField(db_index=True, max_length=50)),
                ('text_1', models.TextField(db_index=True, max_length=200)),
                ('slogan_2', models.CharField(db_index=True, max_length=50)),
                ('text_2', models.TextField(db_index=True, max_length=200)),
                ('slogan_3', models.CharField(db_index=True, max_length=50)),
                ('text_3', models.TextField(db_index=True, max_length=200)),
            ],
        ),
    ]
