# Generated by Django 4.1.1 on 2022-09-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_chefs_events_gallery_ourinformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userreservation',
            name='req_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userreservation',
            name='req_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
