# Generated by Django 4.1.1 on 2022-09-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userreservation_email_userreservation_req_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreservation',
            name='req_time',
            field=models.TimeField(),
        ),
    ]
