# Generated by Django 4.1.1 on 2022-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userreservation_req_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
        migrations.AddField(
            model_name='gallery',
            name='position',
            field=models.SmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
