# Generated by Django 4.1.1 on 2022-09-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_gallery_title_gallery_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
