# Generated by Django 4.1.1 on 2022-09-15 18:57

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_chefs_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='photo',
            field=models.ImageField(default=1, upload_to=main.models.Testimonials.get_file_name),
            preserve_default=False,
        ),
    ]
