# Generated by Django 4.1.1 on 2022-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_testimonials_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_visible',
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
