# Generated by Django 4.1.1 on 2022-09-16 18:31

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_about_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='photo',
            field=models.ImageField(default=1, upload_to=main.models.About.get_file_name),
            preserve_default=False,
        ),
    ]
