# Generated by Django 4.1.1 on 2022-09-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_about_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourinformation',
            name='google_coordinates',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
