# Generated by Django 4.1.1 on 2022-09-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_ourinformation_google_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourinformation',
            name='open_days',
            field=models.CharField(default='Monday-Sunday:', max_length=200),
        ),
        migrations.AlterField(
            model_name='ourinformation',
            name='google_coordinates',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
