# Generated by Django 4.1.1 on 2022-09-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_usermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
